variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: clone

cache:
  paths:
    - .cache/pip

stages:
  - lint
  - test
  - doc
  - build

.except-default: &except-default
  except:
    - tags

.python_version:
  <<: *except-default
  image: python:3.7
  before_script:
    - pip install -r .ci/requirements.txt
    - REQUIREMENTS=$(mktemp) && python setup.py requirements > ${REQUIREMENTS} && pip install -r ${REQUIREMENTS} && rm ${REQUIREMENTS}
    - pip install -r .ci/requirements_modules.txt

lint:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes.sh

lint_strict:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes-strict.sh

bandit:
  stage: lint
  extends: .python_version
  script:
    - pip install bandit importlib-metadata==4.8.2
    - bandit -r woob
    - bandit -r modules
    - bandit -r contrib

load_modules:
  stage: test
  extends: .python_version
  script:
    - ./tools/local_run.sh config update

test:
  stage: test
  extends: .python_version
  script:
    - ./tools/run_tests.sh --no-modules
    - coverage xml -o coverage.xml -i
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

doc:
  stage: doc
  extends: .python_version
  script:
    - cd ./docs && make html

build:
  stage: build
  extends: .python_version
  script:
    - ./tools/local_install.sh --local-modules ~/bin
